# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nestedappinstancemetrics/nestedappinstanceinventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9nestedappinstancemetrics/nestedappinstanceinventory.proto\x12\'org.lfedge.eve.nestedappinstancemetrics\"I\n\x0fNestedAppStatus\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x14\n\x0c\x64isable_logs\x18\x03 \x01(\x08\"\\\n\x12NestedAppInventory\x12\x46\n\x04\x61pps\x18\x01 \x03(\x0b\x32\x38.org.lfedge.eve.nestedappinstancemetrics.NestedAppStatusB8Z6github.com/lf-edge/eve-api/go/nestedappinstancemetricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nestedappinstancemetrics.nestedappinstanceinventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/lf-edge/eve-api/go/nestedappinstancemetrics'
  _globals['_NESTEDAPPSTATUS']._serialized_start=102
  _globals['_NESTEDAPPSTATUS']._serialized_end=175
  _globals['_NESTEDAPPINVENTORY']._serialized_start=177
  _globals['_NESTEDAPPINVENTORY']._serialized_end=269
# @@protoc_insertion_point(module_scope)
