# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nestedappinstancemetrics/nestedappinstancelog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3nestedappinstancemetrics/nestedappinstancelog.proto\x12\'org.lfedge.eve.nestedappinstancemetrics\"U\n\x17NestedAppInstanceLogMsg\x12\x15\n\rnested_app_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontainer_name\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\tB8Z6github.com/lf-edge/eve-api/go/nestedappinstancemetricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nestedappinstancemetrics.nestedappinstancelog_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/lf-edge/eve-api/go/nestedappinstancemetrics'
  _globals['_NESTEDAPPINSTANCELOGMSG']._serialized_start=96
  _globals['_NESTEDAPPINSTANCELOGMSG']._serialized_end=181
# @@protoc_insertion_point(module_scope)
