# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hardwarehealth/hardware_health.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$hardwarehealth/hardware_health.proto\x12\x1dorg.lfedge.eve.hardwarehealth\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n\x0fZHardwareHealth\x12\x0e\n\x06\x64\x65v_id\x18\x01 \x01(\t\x12\x31\n\rat_time_stamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\x02mr\x18\x03 \x01(\x0b\x32..org.lfedge.eve.hardwarehealth.ECCMemoryReport\"E\n\x0c\x44immRankInfo\x12\x11\n\trank_name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x65_count\x18\x02 \x01(\x03\x12\x10\n\x08ue_count\x18\x03 \x01(\x03\"\x92\x01\n\x17\x45\x43\x43MemoryControllerInfo\x12\x17\n\x0f\x63ontroller_name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x65_count\x18\x02 \x01(\x03\x12\x10\n\x08ue_count\x18\x03 \x01(\x03\x12:\n\x05ranks\x18\x04 \x03(\x0b\x32+.org.lfedge.eve.hardwarehealth.DimmRankInfo\"e\n\x0f\x45\x43\x43MemoryReport\x12R\n\x12memory_controllers\x18\x01 \x03(\x0b\x32\x36.org.lfedge.eve.hardwarehealth.ECCMemoryControllerInfoBM\n\x1dorg.lfedge.eve.hardwarehealthZ,github.com/lf-edge/eve-api/go/hardwarehealthb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardwarehealth.hardware_health_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035org.lfedge.eve.hardwarehealthZ,github.com/lf-edge/eve-api/go/hardwarehealth'
  _globals['_ZHARDWAREHEALTH']._serialized_start=105
  _globals['_ZHARDWAREHEALTH']._serialized_end=249
  _globals['_DIMMRANKINFO']._serialized_start=251
  _globals['_DIMMRANKINFO']._serialized_end=320
  _globals['_ECCMEMORYCONTROLLERINFO']._serialized_start=323
  _globals['_ECCMEMORYCONTROLLERINFO']._serialized_end=469
  _globals['_ECCMEMORYREPORT']._serialized_start=471
  _globals['_ECCMEMORYREPORT']._serialized_end=572
# @@protoc_insertion_point(module_scope)
