# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics/nestedappruntimemetrics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%metrics/nestedappruntimemetrics.proto\x12\x16org.lfedge.eve.metrics\"5\n\x0c\x46sUsedMetric\x12\x0f\n\x07used_mb\x18\x01 \x01(\x01\x12\x14\n\x0c\x61llocated_mb\x18\x02 \x01(\x01\"\xa8\x02\n\x1aNestedAppRuntimeDiskMetric\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08total_mb\x18\x02 \x01(\x01\x12\x0f\n\x07used_mb\x18\x03 \x01(\x01\x12\x14\n\x0c\x61llocated_mb\x18\x04 \x01(\x01\x12\x64\n\x12\x64\x65pendent_space_mb\x18\x05 \x03(\x0b\x32H.org.lfedge.eve.metrics.NestedAppRuntimeDiskMetric.DependentSpaceMbEntry\x1a]\n\x15\x44\x65pendentSpaceMbEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.org.lfedge.eve.metrics.FsUsedMetric:\x02\x38\x01\x42?\n\x16org.lfedge.eve.metricsZ%github.com/lf-edge/eve-api/go/metricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics.nestedappruntimemetrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026org.lfedge.eve.metricsZ%github.com/lf-edge/eve-api/go/metrics'
  _NESTEDAPPRUNTIMEDISKMETRIC_DEPENDENTSPACEMBENTRY._options = None
  _NESTEDAPPRUNTIMEDISKMETRIC_DEPENDENTSPACEMBENTRY._serialized_options = b'8\001'
  _globals['_FSUSEDMETRIC']._serialized_start=65
  _globals['_FSUSEDMETRIC']._serialized_end=118
  _globals['_NESTEDAPPRUNTIMEDISKMETRIC']._serialized_start=121
  _globals['_NESTEDAPPRUNTIMEDISKMETRIC']._serialized_end=417
  _globals['_NESTEDAPPRUNTIMEDISKMETRIC_DEPENDENTSPACEMBENTRY']._serialized_start=324
  _globals['_NESTEDAPPRUNTIMEDISKMETRIC_DEPENDENTSPACEMBENTRY']._serialized_end=417
# @@protoc_insertion_point(module_scope)
